### ISSUE TITLE
ImportError: No module named annotations

### ISSUE THREAD

**Issue by hukangrong** [bolme/pyvision#5]
I use cython --2.0 to compile pyvision, but I still can't import vision successful.

> import vision
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "vision/__init__.py", line 1, in <module>
>     from annotations import *
> ImportError: No module named annotations

**Comment by housong404** [comment]
I have the sane question,do you know the solution?thank you very much

**Comment by bolme** [comment]
I don't think this is an issue with my version of pyvision.  Are you confused with another project?  How did you get the code?

**Comment by housong404** [comment]
> I don't think this is an issue with my version of pyvision. Are you confused with another project? How did you get the code?

I changed a method and it has been configured.
